spring:
  application:
    name: webPractice
  datasource:
    url: 'jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  resources:
    static-locations: classpath:/
  mvc:
    view:
      suffix: .html

server:
  port: 8888

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    root: warn
    com:
      shicepku: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'


