spring:
  application:
    name: webPractice
  datasource:
    url: 'jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8'
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:templates/


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    root: warn
    com:
      zxh: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'




